// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_wD8ZN_GuE03lkRZoeIJ1n0XzX224d2A',
    appId: '1:66500442999:web:cd02ce8832cf3c7e8c3f72',
    messagingSenderId: '66500442999',
    projectId: 'winitcode',
    authDomain: 'winitcode.firebaseapp.com',
    databaseURL: 'https://winitcode.firebaseio.com',
    storageBucket: 'winitcode.firebasestorage.app',
    measurementId: 'G-L8BEWKZFZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV5sjWkgDiXd5Lc3K8rGtp6FqCNnsB53A',
    appId: '1:66500442999:android:808b46a2c808868e8c3f72',
    messagingSenderId: '66500442999',
    projectId: 'winitcode',
    databaseURL: 'https://winitcode.firebaseio.com',
    storageBucket: 'winitcode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqzJN2HsIeXrbSNPITeHOpxQ46ETWAh0A',
    appId: '1:66500442999:ios:30f39f4ab83f44b18c3f72',
    messagingSenderId: '66500442999',
    projectId: 'winitcode',
    databaseURL: 'https://winitcode.firebaseio.com',
    storageBucket: 'winitcode.firebasestorage.app',
    androidClientId: '66500442999-9cl5s87tsdb4orghn70kibven7077f18.apps.googleusercontent.com',
    iosBundleId: 'com.winit.app.winit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqzJN2HsIeXrbSNPITeHOpxQ46ETWAh0A',
    appId: '1:66500442999:ios:30f39f4ab83f44b18c3f72',
    messagingSenderId: '66500442999',
    projectId: 'winitcode',
    databaseURL: 'https://winitcode.firebaseio.com',
    storageBucket: 'winitcode.firebasestorage.app',
    androidClientId: '66500442999-9cl5s87tsdb4orghn70kibven7077f18.apps.googleusercontent.com',
    iosBundleId: 'com.winit.app.winit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_wD8ZN_GuE03lkRZoeIJ1n0XzX224d2A',
    appId: '1:66500442999:web:47ffc147c17105f18c3f72',
    messagingSenderId: '66500442999',
    projectId: 'winitcode',
    authDomain: 'winitcode.firebaseapp.com',
    databaseURL: 'https://winitcode.firebaseio.com',
    storageBucket: 'winitcode.firebasestorage.app',
    measurementId: 'G-L8C5YX508Y',
  );
}
